version: "3.8"
services:
#----------------------------------------------------------------
  modulefederation-second-microfront:
    build: 
      context: ./../frontend/modulefederation
      dockerfile: apps/second-microfront/Dockerfile
    container_name: modulefederation-second-microfront
    restart: on-failure
    expose:
      - '4202'
    ports:
      - "4202:80"
    networks:
      - modulefederation-network
#----------------------------------------------------------------
networks:
  modulefederation-network:
